name: geo_pakistan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  get: ^4.6.6
  gap: ^3.0.1  # Use the latest version

flutter:
  assets:
    - assets/pic/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/logo.png

  android_12:
    color: "#42a5f5"
    image: assets/logo.png
